resources:
- name: silk
  type: git
  source:
    uri: https://github.com/cloudfoundry/silk
    branch: master

- name: weekly-trigger
  type: time
  source: {interval: 168h}

jobs:
- name: silk-test-postgres
  plan:
  - in_parallel:
    - get: silk
      trigger: true
    - get: weekly-trigger
      trigger: true
  - task: test-postgres
    file: silk/ci/test-postgres.yml
    privileged: true

- name: silk-test-mysql
  plan:
  - in_parallel:
    - get: silk
      trigger: true
    - get: weekly-trigger
      trigger: true
  - task: test-mysql
    file: silk/ci/test-mysql.yml
    privileged: true

- name: silk-test-mysql-5.6
  plan:
  - in_parallel:
    - get: silk
      trigger: true
    - get: weekly-trigger
      trigger: true
  - task: test-mysql
    file: silk/ci/test-mysql-5.6.yml
    privileged: true
