---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: c2cnetworking/dev-mysql-5.6
    tag: 0.99.0

inputs:
  - name: silk

run:
  path: /bin/bash
  args:
    - -c
    - |
      cd silk
      export GOPATH=$PWD
      export PATH=$PATH:$GOPATH/bin
      export DB=mysql-5.6
      scripts/test.sh
